name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - release/integrate_0713

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install packages
        run: yarn
      - name: Build
        run: yarn build
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: social-tw-website
      #     path: ./
    
  circuits-test:
    name: Circuits Test
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: social-tw-website
      # - name: Test artifact download
      #   run: ls -R
      - name: Check out repository code
        uses: actions/checkout@v3  
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install circom
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
          source "$HOME/.cargo/env"
          ls -R
          cd /tmp
          git clone https://github.com/iden3/circom.git
          cd circom
          cargo build --release
          cargo install --path circom
      - name: Test
        run: yarn circuits test
    
  contracts-test:
    name: Contracts Test
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: social-tw-website
      - name: Check out repository code
        uses: actions/checkout@v3  
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # - name: Test
      #   run: yarn contracts test
  
  relay-test:
    name: Relay Test
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: social-tw-website
      - name: Check out repository code
        uses: actions/checkout@v3  
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # - name: Test
      #   run: yarn relay test
    
  frontend-test:
    name: Frontend Test
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # - name: Download artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: social-tw-website
      - name: Check out repository code
        uses: actions/checkout@v3  
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # - name: Test
      #   run: yarn frontend test
    
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3  
      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install packages
        run: yarn
      # - name: Lint
      #   run: yarn lint --check
         